### PR TITLE
Added unionTypes for multiple typenames list

### PR DESCRIPTION
**Pull request by EloB**
Related: https://github.com/monojack/graphql-normalizr/issues/12

https://graphql.org/learn/schema/#union-types

### CODE REVIEW

**Comment by monojack** [comment]
What do you think about using an object instead?

```js
{
  videos: {
    movies: [6, 7],
    shows: [8]
  },
}
```

**Comment by EloB** [comment]
> What do you think about using an object instead?
> 
> ```js
> {
>   videos: {
>     movies: [6, 7],
>     shows: [8]
>   },
> }
> ```

The only problem I can see with this is that the order is not intact...

**Comment by EloB** [comment]
Also one feature that I miss is to handle `pageInfo` and `cursor` is some way but I think that belongs in another PR.

**Comment by EloB** [comment]
Super nice library you built by the way! I'm really excited to start using it. Just need this PR to start working with it :)

**Comment by EloB** [comment]
Another solution would be to have a mapper but then it requires the id are unique or that we transform the id to be unique with `${__typename}::${id}`.

```js
{
  "mapper": {
    "bd8758631a89889929df5a5cd2a7c0558d01b01d": "movies",
    "5ab5a5904738eafa8cd960a5ac2c718c023c48e8": "show",
    "a2d298fbb4493bb44562105e41b3e36ce296f516": "movies"
  },
  "collections: {
    "7f07fe330b6d887205a4f82425c3a0bddbed5e40": {
      "name": "Continue Watching",
      "videos": [
        "bd8758631a89889929df5a5cd2a7c0558d01b01d",
        "5ab5a5904738eafa8cd960a5ac2c718c023c48e8",
        "a2d298fbb4493bb44562105e41b3e36ce296f516"
      ]
    }
  },
  "movies": {
    "bd8758631a89889929df5a5cd2a7c0558d01b01d": {},
    "a2d298fbb4493bb44562105e41b3e36ce296f516": {}
  },
  "shows": {
    "5ab5a5904738eafa8cd960a5ac2c718c023c48e8": {}
  }
}
```

**Comment by monojack** [comment]
Thank you 👍

Regarding the other solutions, adding a `mapper` seems like just another level of indirection. Also, having to split may be error-prone.

I tend towards your initial proposal and would gladly accept it if you'd document it in the README.

**Comment by EloB** [comment]
Can we merge this first and add docs later?

**Comment by EloB** [comment]
I will probably make more PRs in the future. Like performance optimization. I’m going to use this for Smart TVs and their CPU is like single core 1000-2000mhz. 😂

**Comment by EloB** [comment]
I'm fine with this. Just needs this feature without it I can't start working... 😄

**Comment by monojack** [comment]
> I'm fine with this. Just needs this feature without it I can't start working... 😄

done. v2.5.0

**Pull request merged**
